### ISSUE TITLE
Deprecate this library

### ISSUE THREAD

**Issue by kevinburkeotto** [vdemedes/secure-compare#3]
Node.js has a `timingSafeEqual` function built in as of version 6.6.0: https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b

It seems better to a) use that function if it's available and/or b) note in the README that people don't need to load a third party library to do that anymore.

**Comment by vadimdemedes** [comment]
Thanks for the tip, added the note.
